# Generated by Django 5.0 on 2023-12-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, db_column='Nombre_Cliente', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Teléfono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.IntegerField(db_column='ID_Compra', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, db_column='Fecha_Compra', null=True)),
                ('total_compra', models.DecimalField(blank=True, db_column='Total_Compra', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_Producto', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripción', max_length=255, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='Precio_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('stock_disponible', models.IntegerField(blank=True, db_column='Stock_Disponible', null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, db_column='Nombre_Proveedor', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Teléfono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.IntegerField(db_column='ID_Detalle_Compra', primary_key=True, serialize=False)),
                ('cantidad_comprada', models.IntegerField(blank=True, db_column='Cantidad_Comprada', null=True)),
                ('precio_compra_unitario', models.DecimalField(blank=True, db_column='Precio_Compra_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, db_column='Subtotal', decimal_places=2, max_digits=10, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='ID_Compra', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.compras')),
                ('id_producto', models.ForeignKey(blank=True, db_column='ID_Producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.productos')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='ID_Proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.proveedores'),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(db_column='ID_Venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='Fecha_Venta', null=True)),
                ('total_venta', models.DecimalField(blank=True, db_column='Total_Venta', decimal_places=2, max_digits=10, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='ID_Cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.clientes')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.IntegerField(db_column='ID_Detalle_Venta', primary_key=True, serialize=False)),
                ('cantidad_vendida', models.IntegerField(blank=True, db_column='Cantidad_Vendida', null=True)),
                ('precio_venta_unitario', models.DecimalField(blank=True, db_column='Precio_Venta_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, db_column='Subtotal', decimal_places=2, max_digits=10, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='ID_Producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.productos')),
                ('id_venta', models.ForeignKey(blank=True, db_column='ID_Venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.ventas')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
