# Generated by Django 5.0 on 2023-12-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, db_column='Nombre_Cliente', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Teléfono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.IntegerField(db_column='ID_Compra', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, db_column='Fecha_Compra', null=True)),
                ('total_compra', models.DecimalField(blank=True, db_column='Total_Compra', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_Producto', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripción', max_length=255, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='Precio_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('stock_disponible', models.IntegerField(blank=True, db_column='Stock_Disponible', null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, db_column='Nombre_Proveedor', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Teléfono', max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='id_proveedor',
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='ID_Compra', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='ID_Producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='ID_Producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='ID_Proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.proveedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(db_column='ID_Venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='Fecha_Venta', null=True)),
                ('total_venta', models.DecimalField(blank=True, db_column='Total_Venta', decimal_places=2, max_digits=10, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='ID_Cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='ID_Venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.venta'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
